assets: true
clone_addr: http://localhost:3000/EDS/Amirdrassil
comments: true
description: This is Amirdrassil
is_private: false
issues: true
labels: true
milestones: true
name: Amirdrassil
original_url: https://git.devops.hkn/EDS/Amirdrassil
owner: EDS
pulls: true
releases: true
service_type: 3
wiki: true
