assets: true
clone_addr: http://localhost:3000/EDS/Icecrown
comments: true
description: This is Icecrown
is_private: false
issues: true
labels: true
milestones: true
name: Icecrown
original_url: https://git.devops.hkn/EDS/Icecrown
owner: EDS
pulls: true
releases: true
service_type: 3
wiki: true
