assets: true
clone_addr: http://localhost:3000/EDS/tmp
comments: true
description: This is tmp
is_private: false
issues: true
labels: true
milestones: true
name: tmp
original_url: https://git.devops.hkn/EDS/tmp
owner: EDS
pulls: true
releases: true
service_type: 3
wiki: true
